name = "Spencer C. Imbleau"
profile-picture = "GitHub"
bio = "Aerospace engineer focused on CAD, simulation, and computer graphics."
github = "nuzzles"
mastodon = "@scim@mastodon.online"
discord = ".nuzzles"
discord-userid = "144492524340379648"
website = "https://spencer.imbleau.com"
